spring:
  application:
    name: expense-plan-reactive-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactions

server:
  port: 9000
  servlet:
    context-path: /expense-plan-reactive-service





