spring:
  datasource:
    url: jdbc:oracle:thin:@kingsdatabase.cbxkwasywxio.us-east-1.rds.amazonaws.com:1521:kingsdb
    username: personalfinance_konvergion
    password: Iofdtiger#1086
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
  application:
    name: expense-plan-reactive-service

server:
  port: 9000
  servlet:
    context-path: /expense-plan-reactive-service





